WebApp/Models/PickupPointViewModel.cs
using Fr.EQL.AI110.DLD_GD.Entities;

namespace WebApp.Models
{
    public class PickupPointViewModel
    {
        //public Schedule Schedule { get; set; }

        public PickupPoint Pickup { get; set; }

        public int IdPartner { get; set; } = 0;

        public List<Weekday> Days { get; set; }

        public List<City> CityList { get; set; }

        
        public Dictionary<string, Schedule> Planning { get; set; } = new Dictionary<string, Schedule>();
        
        public List<PickupPointDetails> PickupPoints { get; set; }
        
        public List<Partner> Partners { get; set; }

        public PickupPointDetails PickupDetails { get; set; }

    }
}

WebApp/Controllers/PickupPointController.cs
using Fr.EQL.AI110.DLD_GD.Business;
using Fr.EQL.AI110.DLD_GD.Entities;
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class PickupPointController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            PickupPointViewModel model = new PickupPointViewModel();

            PickupPointBusiness ppBU = new PickupPointBusiness();
            @ViewBag.PickupPointsDetails = ppBU.GetAllPickupDetails();

            PartnerBusiness partnerBU = new PartnerBusiness();
            model.Partners = partnerBU.GetPartners();

            CityBusiness cityBU = new CityBusiness();
            ViewBag.Cities = cityBU.GetCities();

            return View(model);
        }


        [HttpPost]
        public IActionResult Index(PickupPointViewModel model)
        {
            
            PickupPointBusiness ppBU = new PickupPointBusiness();
            if(model.IdPartner != 0)
            {
                @ViewBag.PickupPointsDetails = ppBU.GetPickupPointsByIdPartner(model.IdPartner);
            }
            else
            {
                @ViewBag.PickupPointsDetails = ppBU.GetAllPickupDetails();
            }

            PartnerBusiness partnerBU = new PartnerBusiness();
            model.Partners = partnerBU.GetPartners();

            CityBusiness cityBU = new CityBusiness();
            ViewBag.Cities = cityBU.GetCities();

            return View(model);
        }



        [HttpGet]
        [Route("PickupPoint/Update/{pickupId}")]
        public IActionResult Update(int pickupId)
        {
            PickupPointViewModel model = new PickupPointViewModel();
            PickupPointBusiness ppBU = new PickupPointBusiness();
            model.Pickup = ppBU.GetPickupPoint(pickupId);
            model.PickupDetails = ppBU.GetPickupDetailsById(pickupId);

            CityBusiness cityBU = new CityBusiness();
            ViewBag.Cities = cityBU.GetCities();

            PartnerBusiness partnerBU = new PartnerBusiness();
            ViewBag.Partners = partnerBU.GetPartners();

            return View(model);
        }

        
        [HttpPost]
        [Route("PickupPoint/Update/{pickupId}")]
        public IActionResult Update(PickupPointViewModel model, int pickupId)
        {
            CityBusiness cityBU = new CityBusiness();
            ViewBag.Cities = cityBU.GetCities();

            if (model.Pickup.IdPartner != 0)
            {
                try
                {
                    PickupPointBusiness ppBU = new PickupPointBusiness();
                    model.Pickup.Id = pickupId;
                    ppBU.SavePickupPoint(model.Pickup);

                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ViewBag.ErrorMessage = ex.Message;
                    return View("Error");
                }
            }
            else
            {
                return View(model);
            }
        }

        [Route("PickupPoint/Desactivate/{pickupId}")]
        public IActionResult Desactivate(int pickupId)
        {
            PickupPointBusiness bu = new PickupPointBusiness();
            PickupPoint pickup = bu.GetPickupPoint(pickupId);
            bu.DesactivatePickupPoint(pickup);
            return RedirectToAction("Index");
        }


        [HttpGet]
        public IActionResult Create()
        {
            CityBusiness cityBU = new CityBusiness();
            ViewBag.Cities = cityBU.GetCities();

            WeekdayBusiness weekdayBU = new WeekdayBusiness();
            ViewBag.Days = weekdayBU.GetWeekdays();

            PartnerBusiness partnerBU = new PartnerBusiness();
            ViewBag.Partners = partnerBU.GetPartners();

            return View();
        }


        [HttpPost]
        public IActionResult Create(PickupPointDetails model)
        {
            WeekdayBusiness weekdaybu = new WeekdayBusiness();
            List<Weekday> weekdays = weekdaybu.GetWeekdays();

            PickupPointBusiness ppbusiness = new PickupPointBusiness();
            ScheduleBusiness schedulebusiness = new ScheduleBusiness();

            if (model.IdPartner != 0)
            {
                try
                {
                    model.CreationDate = DateTime.Now;

                    ppbusiness.SavePickupPoint(model);
                    int pickupId = model.Id;


                    foreach (Weekday day in weekdays)
                    {
                        Schedule schedule = model.Planning[day.Day];
                        schedule.IdDay = day.Id;
                        schedule.IdPickupPoint = model.Id;

                        schedulebusiness.InsertSchedule(schedule);
                    }

                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ViewBag.ErrorMessage = ex.Message;
                    return View("Error");
                }
            }
            else
            {
                return View(model);
            }

        }


        /*
        [HttpGet]
        [Route("PickupPoint/MyPickupPoints/{userID}")]
        public IActionResult MyPickupPoints(int userID)
        {
            PickupPointViewModel model = new PickupPointViewModel();

            PickupPointBusiness ppBU = new PickupPointBusiness();
            model.PickupPoints = ppBU.GetPickupPointsByIdPartner(userID);
            WeekdayBusiness weekdayBU = new WeekdayBusiness();

            ScheduleBusiness scheduleBU = new ScheduleBusiness();
            foreach (PickupPointDetails pickupPointDetails in model.PickupPoints)
            {
                pickupPointDetails.ScheduleDetailsList = scheduleBU.GetSchedulesByIdPickup(pickupPointDetails.Id);
                foreach (ScheduleDetails scheduledetails in pickupPointDetails.ScheduleDetailsList)
                {
                    scheduledetails.DayName = weekdayBU.GetDayById(scheduledetails.IdDay).Day;
                }
            }

            return View(model);
        }*/



        [HttpGet]
        public IActionResult Details(int id)
        {
            PickupPointBusiness pickupBU = new PickupPointBusiness();
            PickupPointDetails pickupPointDetails = pickupBU.GetPickupDetailsById(id);

            WeekdayBusiness weekdayBU = new WeekdayBusiness();
            CityBusiness cityBU = new CityBusiness();
            ScheduleBusiness scheduleBU = new ScheduleBusiness();

            pickupPointDetails.ZipCode = cityBU.GetCityById(pickupPointDetails.IdCity).ZipCode;
            pickupPointDetails.CityName = cityBU.GetCityById(pickupPointDetails.IdCity).CityName;
            pickupPointDetails.ScheduleDetailsList = scheduleBU.GetSchedulesByIdPickup(pickupPointDetails.Id);
            foreach (ScheduleDetails scheduledetails in pickupPointDetails.ScheduleDetailsList)
            {
                scheduledetails.DayName = weekdayBU.GetDayById(scheduledetails.IdDay).Day;
            }

            return View(pickupPointDetails);
        }


    }
       
 }

WebApp/Views/PickupPoint/Create.cshtml
@using Fr.EQL.AI110.DLD_GD.Entities
@model PickupPointDetails

@{
    ViewData["Title"] = "Création d'un point de dépôt";

}
<head>
<link rel="shortcut icon" type="image/ico" href="~/favicon.ico">
</head>

<h1><img src="~/Image/Strawberry.png" alt="strawberry" style="max-width:30px; max-height:30px;"/>Création d'un point de dépôt</h1>

<section class="newpickuppoint">
<br/>
<br />
<div >

<form method="post">
<div class="formblockelement">

        <label asp-for="@Model.IdPartner">Partenaire :</label> 
                <select asp-for="@Model.IdPartner">
                @foreach (Partner partner in @ViewBag.Partners)
                {
                    <option value="@partner.Id">@partner.InfrastructureName</option>
                }
            </select>
        <br/>
        <label asp-for="@Model.PickupPointName">Nom du Point de dépôt : </label> 
        <input asp-for="@Model.PickupPointName"/>
        
        <br />
           
</div>
        <div class="formblockelement">
            <h3 class = "pickuppoint-h3">Adresse :</h3>
                <table class="pickuppointtable">
                    <tr>
                    <td> <label asp-for="@Model.StreetNumber">Numéro de rue</label></td>
                    <td><input asp-for="@Model.StreetNumber"/></td>
                    <br />
                </tr>
                <tr>
                    <td> <label asp-for="@Model.StreetName">Nom de rue</label></td>
                    <td> <input asp-for="@Model.StreetName"/> </td>
                    <br />
                </tr>
                <tr>
                    <td> <label asp-for="@Model.IdCity">Ville</label> </td>
                    <td>  <select asp-for="@Model.IdCity" id="citylist">
                        @foreach (City city in @ViewBag.Cities)
                        {
                            <option value="@city.Id">@city.ZipCode - @city.CityName </option>
                        }
                    </select> </td>
                </tr>
            </table>
        </div>
        <br />
        <img src="~/Image/Strawberry.png" alt="strawberry" style="max-width:30px; max-height:30px;"/>
        <img src="~/Image/Strawberry.png" alt="strawberry" style="max-width:30px; max-height:30px;"/>
        <img src="~/Image/Strawberry.png" alt="strawberry" style="max-width:30px; max-height:30px;"/>
        <br/>
        <div class="formblockelement">
            <br />
            <h3 class = "pickuppoint-h3">Horaires d'ouverture :</h3>
            <br />
            <table class="pickuppointtable">
                   
            @foreach (Weekday day in @ViewBag.Days)
            {
            <tr>
                <td>
                    <label class="switch">
                        <input type="checkbox" id="@day.Id" name="@day.Id" value="checked"/>
                        <span class="slider round"></span>
                    </label>
                </td>
          
                <td> <label>@day.Day de </label></td>
                <td><input asp-for="Planning[day.Day].OpeningHours"/> </td>
                <td><label> à </label></td>
                <td><input asp-for="Planning[day.Day].ClosingHours"/></td>
            </tr>
            }
            </table>
            <br />

            <input type="submit" value="Enregistrer" class="pickup-ok-button"/>
        </div>
    </form>

                
   <button class="pickup-cancel-button"> @Html.ActionLink("Annuler","Index") </button>

</div>
</section>

WebApp/Views/PickupPoint/Index.cshtml
@using Fr.EQL.AI110.DLD_GD.Entities
@model PickupPointViewModel

@{
    ViewData["Title"] = "Points de dépôt";
}


       <h1>Liste des points de dépôt</h1> 

<form method="post">
<label class="white-font">Partenaire : </label>
<select asp-for="IdPartner">
    <option value = "0"> Tous </option>
       @foreach (Partner partner in Model.Partners)
        {
         <option value="@partner.Id">@partner.InfrastructureName</option>
        }
 </select>
 <input class="cute-button" type="submit" value="Filtrer"/>
 </form>

<div class="add-button">
<a asp-controller="PickupPoint" asp-action="Create">
   <button title="Ajouter un point de dépôt" class="add-pickup-btn"> ➕ Ajouter  </button>
</a>
</div>

<br />
<section>
            <table class="pickuppointstable">
                <thead>
                    <tr>
                        <th>Nom de l'infrastructure</th>
                        <th>Nom du point de dépot</th>
                        <th>Adresse</th>
                        <th></th>
                        <th></th>
                        <th></th>

                    </tr>
                </thead>
                @foreach (PickupPointDetails pickupPointDetails in @ViewBag.PickupPointsDetails)
                {
                    if(pickupPointDetails.DeletionDate == null)
                    {
                        <tr>
                            <td>@pickupPointDetails.PickupPartner.InfrastructureName</td>
                            <td>@pickupPointDetails.PickupPointName</td>
                            <td>@pickupPointDetails.StreetNumber @pickupPointDetails.StreetName, @pickupPointDetails.ZipCode @pickupPointDetails.CityName</td>
                            <td title="Voir le détail"> <a asp-controller="Storage" asp-action="Index" asp-route-userID="@pickupPointDetails.IdPartner" asp-route-idpickuppoint="@pickupPointDetails.Id">&#128065;</a></td>
                            <td title="Modifier"> <a asp-controller="PickupPoint" asp-action="Update" asp-route-id="@pickupPointDetails.Id">&#128393;</a></td>
                            <td title="Retirer"> <a asp-controller="PickupPoint" asp-action="Desactivate" asp-route-id="@pickupPointDetails.Id">&#128465;</a></td>
                        </tr>
                    }
                }
            </table>

            @*
            <span><label style="font-weight:bold;">Horaires :</label></span>
                <br />
                <table>
                <tbody>
                @foreach (ScheduleDetails scheduleDetails in pickupPointDetails.Schedule)
                {
                <tr>
                <td>@scheduleDetails.DayName</td>
                <td>
                @if (@scheduleDetails.OpeningHours == null || @scheduleDetails.ClosingHours == null)
                {
                <span>Fermé</span>
                }
                else
                {
                <span> de @scheduleDetails.OpeningHours à @scheduleDetails.ClosingHours </span> <br />
                }
                </td>
                </tr>
                }
                </tbody>
                </table>
            *@
            <br />
</section>

WebApp/Views/PickupPoint/Update.cshtml
@using Fr.EQL.AI110.DLD_GD.Entities
@model PickupPointViewModel

@{
    ViewData["Title"] = "Modifier un point de dépôt";
    List<City> cities = ViewBag.Cities;
    List<Partner> partners = ViewBag.Partners;
}

<head>
    <link rel="shortcut icon" type="image/ico" href="~/favicon.ico">
</head>

<h1>Modifier un point de dépôt</h1>

<section  class="newpickuppoint">
<form method="post">
        <label asp-for="Pickup.IdPartner">Partenaire</label>
        <select asp-for="Pickup.IdPartner">
           @foreach(Partner partner in partners)
           {
              <option value="@partner.Id">@partner.InfrastructureName</option>
           }
        </select>

        <br/>
        <label asp-for="Pickup.PickupPointName">Nom du Point de dépôt : </label> 
        <input class="pickup-input-size" asp-for="Pickup.PickupPointName" />

        <br/>
            <div class="formblockelement">
                <img src="~/Image/Strawberry.png" alt="strawberry" style="max-width:30px; max-height:30px;"/>
                <img src="~/Image/Strawberry.png" alt="strawberry" style="max-width:30px; max-height:30px;"/>
                <img src="~/Image/Strawberry.png" alt="strawberry" style="max-width:30px; max-height:30px;"/>
            </div>
            <br/>

            <div class="formblockelement">
    <h3>Adresse :</h3>
     <table class="pickuppointtable">
        <tr>
            <td> <label asp-for="Pickup.StreetNumber">Numéro de rue</label></td>
            <td><input class="pickup-input-size" asp-for="Pickup.StreetNumber"/></td>
        </tr>
        <tr>
            <td> <label asp-for="Pickup.StreetName">Nom de rue</label></td>
            <td> <input class="pickup-input-size" asp-for="Pickup.StreetName"/></td>
            <td></td>
        </tr>
      
        <tr>
            <td><label asp-for="Pickup.IdCity">Ville</label> </td>
            <td><select asp-for="Pickup.IdCity">
                @foreach(City city in cities)
                {
                    <option value="@city.Id">@city.ZipCode - @city.CityName</option>
                }
                </select></td>
        </tr>
     </table>
     </div>
        <br />

       @* <div class="formblockelement">
            <br />
            <h3 class = "pickuppoint-h3">Horaires d'ouverture :</h3>
            <br />
            
            <table class="pickuppointtable">
         
             @foreach (ScheduleDetails scheduleDetails in Model.PickupDetails.ScheduleDetailsList)
            {
            <tr>
                <td>
                    <label class="switch">
                        <input type="checkbox" id="@scheduleDetails.IdDay" name="@scheduleDetails.IdDay"/>
                        <span class="slider round"></span>
                    </label>
                </td>
                <td><input asp-for="@scheduleDetails.Id" type="hidden"/></td>
                <td><input asp-for="@scheduleDetails.IdDay" type="hidden"/></td>
                <td><input asp-for="@scheduleDetails.IdPickupPoint" type="hidden"/></td>
                <td> <label asp-for="@scheduleDetails.DayName">@scheduleDetails.DayName de </label></td>
                <td><input asp-for="@scheduleDetails.OpeningHours"/> </td>
                <td><label> à </label></td>
                <td><input asp-for="@scheduleDetails.ClosingHours"/></td>
            </tr>
            }

            </table>
            </div>
            *@
            <br />
            <button class="pickup-cancel-button"> @Html.ActionLink("Annuler","Index") </button>
            <input type="submit" value="Enregistrer" class="pickup-ok-button"/>
        
</form>
</section>