WebApp/Controllers/DisplayAllPostsController.cs
using Fr.EQL.AI110.DLD_GD.Business;
using Fr.EQL.AI110.DLD_GD.Entities;
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class DisplayAllPostsController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            PostSearchViewModel model = new PostSearchViewModel();

            PostBusiness postBU = new PostBusiness();
            model.Posts = postBU.GetPosts();

            CityBusiness cityBU = new CityBusiness();
            model.Cities = cityBU.GetCities();

            SubscriberBusiness subscriberBU = new SubscriberBusiness();
            model.Subscribers = subscriberBU.GetSubscribers();

            RatingBusiness ratBu = new RatingBusiness();

            foreach (PostDetails post in model.Posts)
            {
                post.CityName = cityBU.GetCityById(post.IdCityOfDeposit).CityName;
                if (subscriberBU.GetSubscriberById(post.IdReceivingSubscriber) != null)
                {
                    post.ReceivingSubscriberLogin = subscriberBU.GetSubscriberById(post.IdReceivingSubscriber).Login;
                }
                if (subscriberBU.GetSubscriberById(post.IdDonatingSubscriber) != null)
                {
                    post.DonatingSubscriberLogin = subscriberBU.GetSubscriberById(post.IdDonatingSubscriber).Login;
                    if (ratBu.GetRatingByIdPost(post.IdDonatingSubscriber, post.Id).Id != 0)
                    {
                        post.IsRated = true;
                    }
                }

            }
            return View(model);
        }

        [HttpPost]
        public IActionResult Index(PostSearchViewModel model)
        {
            PostBusiness postBU = new PostBusiness();
            model.Posts = postBU.GetPostsByIdSubscriber(model.IdDonatingSubscriber);

            CityBusiness cityBU = new CityBusiness();
            model.Cities = cityBU.GetCities();

            SubscriberBusiness subscriberBU = new SubscriberBusiness();
            model.Subscribers = subscriberBU.GetSubscribers();

            RatingBusiness ratBu = new RatingBusiness();

            foreach (PostDetails post in model.Posts)
            {
                post.CityName = cityBU.GetCityById(post.IdCityOfDeposit).CityName;
                if (subscriberBU.GetSubscriberById(post.IdReceivingSubscriber) != null)
                {
                    post.ReceivingSubscriberLogin = subscriberBU.GetSubscriberById(post.IdReceivingSubscriber).Login;
                }
                if (subscriberBU.GetSubscriberById(post.IdDonatingSubscriber) != null)
                {
                    post.DonatingSubscriberLogin = subscriberBU.GetSubscriberById(post.IdDonatingSubscriber).Login;
                    if (ratBu.GetRatingByIdPost(post.IdDonatingSubscriber, post.Id).Id != 0)
                    {
                        post.IsRated = true;
                    }
                }
            }
            return View(model);
        }
        [HttpGet]
        public IActionResult IndexReceiver()
        {
            PostSearchViewModel model = new PostSearchViewModel();

            PostBusiness postBU = new PostBusiness();
            model.Posts = postBU.GetPostsOfReceiver();

            CityBusiness cityBU = new CityBusiness();
            model.Cities = cityBU.GetCities();

            SubscriberBusiness subscriberBU = new SubscriberBusiness();
            model.Subscribers = subscriberBU.GetSubscribers();

            foreach (PostDetails post in model.Posts)
            {
                RatingBusiness ratBu = new RatingBusiness();
                
                post.CityName = cityBU.GetCityById(post.IdCityOfDeposit).CityName;
                if (subscriberBU.GetSubscriberById(post.IdReceivingSubscriber) != null)
                {
                    post.ReceivingSubscriberLogin = subscriberBU.GetSubscriberById(post.IdReceivingSubscriber).Login;
                    if (ratBu.GetRatingByIdPost(post.IdReceivingSubscriber, post.Id).Id != 0)
                    {
                        post.IsRated = true;
                    }
                }
                if (subscriberBU.GetSubscriberById(post.IdDonatingSubscriber) != null)
                {
                    post.DonatingSubscriberLogin = subscriberBU.GetSubscriberById(post.IdDonatingSubscriber).Login;
                }

            }
            return View(model);
        }
        [HttpPost]
        public IActionResult IndexReceiver(PostSearchViewModel model)
        {
            PostBusiness postBU = new PostBusiness();
            if (model.IdDonatingSubscriber != 0)
            {
            model.Posts = postBU.SearchPostsOfReceiver(model.Title, 0, 0, model.IdDonatingSubscriber);
            }
            else
            {
            model.Posts = postBU.GetPostsOfReceiver();
            }
           
            CityBusiness cityBU = new CityBusiness();
            model.Cities = cityBU.GetCities();

            SubscriberBusiness subscriberBU = new SubscriberBusiness();
            model.Subscribers = subscriberBU.GetSubscribers();

            foreach (PostDetails post in model.Posts)
            {
                RatingBusiness ratBu = new RatingBusiness();

                post.CityName = cityBU.GetCityById(post.IdCityOfDeposit).CityName;
                if (subscriberBU.GetSubscriberById(post.IdReceivingSubscriber) != null)
                {
                    post.ReceivingSubscriberLogin = subscriberBU.GetSubscriberById(post.IdReceivingSubscriber).Login;
                    if (ratBu.GetRatingByIdPost(post.IdReceivingSubscriber, post.Id).Id != 0)
                    {
                        post.IsRated = true;
                    }
                }
                if (subscriberBU.GetSubscriberById(post.IdDonatingSubscriber) != null)
                {
                    post.DonatingSubscriberLogin = subscriberBU.GetSubscriberById(post.IdDonatingSubscriber).Login;
                }
            }
            return View(model);
        }

        public IActionResult DisplayPost(int id)
        {
            PostViewModel model = new PostViewModel();

            PostBusiness postBu = new PostBusiness();
            model.Post = postBu.GetPostById(id);

            ProductLineBusiness productLineBu = new ProductLineBusiness();
            model.ProductLine = productLineBu.GetProductLine(id);

            UnitBusiness unitBu = new UnitBusiness();
            model.Unit = unitBu.GetUnit(model.ProductLine.IdUnit);

            if (model.Post.IdStorage != 0)
            {
            StorageBusiness storageBusiness = new StorageBusiness();
            model.Storage = storageBusiness.GetStorage(model.Post.IdStorage);

            PickupPointBusiness pickupPointBusiness = new PickupPointBusiness();
            model.PickupPoint = pickupPointBusiness.GetPickupPoint(model.Storage.IdPickupPoint);
            }
           
            CityBusiness cityBusiness = new CityBusiness();
            model.City = cityBusiness.GetCityById(model.Post.IdCityOfDeposit);

            return View(model);
        }
        public IActionResult Delete(int id)
        {
            PostBusiness postBu = new PostBusiness();
            Post post = postBu.GetPostById(id);
            post.DeletionDate = DateTime.Now;
            postBu.Update(post);
            return RedirectToAction("Index");
        }
        public IActionResult Validate(int id)
        {
            MailNotificationBusiness mailBU = new MailNotificationBusiness();
            SubscriberBusiness subBU = new SubscriberBusiness();
            PostBusiness postBu = new PostBusiness();
            Post post = postBu.GetPostById(id);
            post.ValidationDate = DateTime.Now;
            // Si remise en main propre, date de dépot automatiquement remplie
            if (post.IdStorage == 0)
            {
                post.DepositDate = DateTime.Now;
            }
            postBu.Update(post);

            //envoie la décision par e-mail au bénéficiaire
            string decision = "validé";
            Subscriber recipient = subBU.GetSubscriberById(post.IdReceivingSubscriber);
            mailBU.NewValidationMail(recipient, decision);

            return RedirectToAction("Index");
        }
        public IActionResult Refuse(int id)
        {
            MailNotificationBusiness mailBU = new MailNotificationBusiness();
            SubscriberBusiness subBU = new SubscriberBusiness();

            PostBusiness postBu = new PostBusiness();
            Post post = postBu.GetPostById(id);
            post.ReservationDate = null;
            postBu.Update(post);

            //envoie la décision par e-mail au bénéficiaire
            string decision = "refusé";
            Subscriber subscriber = subBU.GetSubscriberById(post.IdReceivingSubscriber);
            mailBU.NewValidationMail(subscriber, decision);

            return RedirectToAction("Index");
        }
        public IActionResult Ok(int id)
        {
            PostBusiness postBu = new PostBusiness();
            Post post = postBu.GetPostById(id);
            post.IdReceivingSubscriber = 0;
            postBu.Update(post);
            return RedirectToAction("IndexReceiver");
        }
        public IActionResult Cancel(int id)
        {
            PostBusiness postBu = new PostBusiness();
            Post post = postBu.GetPostById(id);
            post.ReservationDate = null;
            post.ValidationDate = null;
            post.IdReceivingSubscriber = 0;
            postBu.Update(post);
            return RedirectToAction("IndexReceiver");
        }
        public IActionResult ConfirmedCollection(int id)
        {
            PostBusiness postBu = new PostBusiness();
            Post post = postBu.GetPostById(id);
            post.CollectionDate = DateTime.Now;
            postBu.Update(post);
            return RedirectToAction("IndexReceiver");
        }
    }
}

WebApp/Controllers/RatingController.cs
using Fr.EQL.AI110.DLD_GD.Business;
using Fr.EQL.AI110.DLD_GD.Entities;
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class RatingController : Controller
    {
        [HttpGet]
        public IActionResult IndexReceiver(int id)
        {
            RatingViewModel model = new RatingViewModel();
            model.IdPost = id;

            PostBusiness postBu = new PostBusiness();
            Post post = postBu.GetPostById(id);

            SubscriberBusiness subBu = new SubscriberBusiness();
            model.RatingSub = subBu.GetSubscriberById(post.IdReceivingSubscriber);
            model.RatedSub = subBu.GetSubscriberById(post.IdDonatingSubscriber);

            model.IsDonator = false;

            return View("Index",model);
        }
        [HttpPost]
        public IActionResult SaveRating(RatingViewModel model)
        {
            PostBusiness postBu = new PostBusiness();
            Post post = postBu.GetPostById(model.IdPost);

            SubscriberBusiness subBu = new SubscriberBusiness();
            RatingBusiness ratingBu = new RatingBusiness();
            model.Rating.IdPost = model.IdPost;

            if (model.IsDonator)
            {
                model.RatingSub = subBu.GetSubscriberById(post.IdDonatingSubscriber);
                model.RatedSub = subBu.GetSubscriberById(post.IdReceivingSubscriber);

                model.Rating.IdSubscriber = post.IdDonatingSubscriber;
                model.Rating.IdReceivingSub = post.IdReceivingSubscriber;
                
            }
            else
            {
                model.RatingSub = subBu.GetSubscriberById(post.IdReceivingSubscriber);
                model.RatedSub = subBu.GetSubscriberById(post.IdDonatingSubscriber);

                model.Rating.IdSubscriber = post.IdReceivingSubscriber;
                model.Rating.IdReceivingSub = post.IdDonatingSubscriber;
            }

            ratingBu.Save(model.Rating);
            model.Message = "Votre note a bien été prise en compte";

            return View("Index",model);
        }

        public IActionResult IndexDonator(int id)
        {
            RatingViewModel model = new RatingViewModel();
            model.IdPost = id;

            PostBusiness postBu = new PostBusiness();
            Post post = postBu.GetPostById(id);

            SubscriberBusiness subBu = new SubscriberBusiness();
            model.RatingSub = subBu.GetSubscriberById(post.IdDonatingSubscriber); 
            model.RatedSub = subBu.GetSubscriberById(post.IdReceivingSubscriber);

            RatingBusiness ratBu = new RatingBusiness();
            model.Rating = ratBu.GetRatingByIdPost(model.RatingSub.Id, model.IdPost);

            model.IsDonator = true;

            return View("Index", model);
        }

        public IActionResult Display()
        {
            RatingViewModel model = new RatingViewModel();

            SubscriberBusiness subBu = new SubscriberBusiness();
            model.Subscribers = subBu.GetSubscribers();

            RatingBusiness ratBu = new RatingBusiness();
            model.Ratings = ratBu.GetRatings(0);

            return View(model);
        }
        [HttpPost]
        public IActionResult Display(RatingViewModel model)
        {
            SubscriberBusiness subBu = new SubscriberBusiness();
            model.Subscribers = subBu.GetSubscribers();

            RatingBusiness ratBu = new RatingBusiness();
            model.Ratings = ratBu.GetRatings(model.RatedSub.Id);

            return View(model);
        }

    }
}

WebApp/Views/DisplayAllPosts/DisplayPost.cshtml
@using Fr.EQL.AI110.DLD_GD.Entities

@model PostViewModel

<div class="publication">
<h1>Annonce</h1>
<article class="border">
<form method="post">
Titre : @Model.Post.Title
<br />
Description : @Model.Post.Description
<br />
Quantité : @Model.ProductLine.Quantity
@Model.Unit.UnitName
<br />
A consommer avant le : 
@Model.ProductLine.BestBeforeDate.ToString("dd/MM/yyyy")
<br />
<img src="~/images/upload/@Model.Post.Picture" width="200"/>
<br />
Ville : @Model.City.CityName
<br />
@{
                if(@Model.Post.IdStorage != 0)
                {
                <span>Point de dépot : @Model.PickupPoint.PickupPointName</span>
                <br />
                <span>Adresse : @Model.PickupPoint.StreetNumber @Model.PickupPoint.StreetName @Model.City.ZipCode @Model.City.CityName</span>
                    <br />
                }
                else
                {
                    <span>Remise en main propre</span>
                    <br />

                }
}



@{
    if (@Model.Post.ReservationDate == null && @Model.Post.ValidationDate == null && @Model.Post.DeletionDate== null)
                {
                    <input asp-action="delete" class="cute-button" type="submit" value="Annuler"/>
                }
                else if (@Model.Post.ReservationDate != null && @Model.Post.ValidationDate == null && @Model.Post.DeletionDate== null)
                {
                    <input asp-action="validate" class="cute-button" type="submit" value="Accepter"/>
                    <input asp-action="refuse" class="cute-button" type="submit" value="Refuser"/>
                }
                
}
<input type="hidden" asp-for="@Model.Post.Id" />
</form>
</article>
</div>

WebApp/Views/DisplayAllPosts/Index.cshtml
@using Fr.EQL.AI110.DLD_GD.Entities
@using WebApp.Models

@model PostSearchViewModel

<h1>Mes dons</h1>
<form method="post">
  <label class="white-font">Adhérent : </label>
        <select asp-for="IdDonatingSubscriber">
            <option value = "0"> Tous </option>
            @foreach (Subscriber subscriber in Model.Subscribers)
            {
                <option value="@subscriber.Id">@subscriber.Login</option>
            }
        </select>
        <input class="cute-button" type="submit" value="Filtrer"/>
</form>

<section>
    <div class="block">
    @foreach (PostDetails postDetails in Model.Posts)
    {
    <div class="block-elements">
        <div class="formblockelement">
                <img src="~/Image/Strawberry.png" alt="strawberry" style="max-width:30px; max-height:30px;"/>
            </div>
        <p class="post-title"> 
             <a asp-controller="DisplayAllPosts" asp-action="displaypost" asp-route-id="@postDetails.Id">@postDetails.Title</a>
            </p>
        <span><label style="font-weight:bold;">Date de publication :</label> @postDetails.PostDate.ToString("dd/MM/yyyy") </span> 
        <br/>
        <span><label style="font-weight:bold;">Disponibilité :</label>
            @if (@postDetails.Availability.Equals("Disponible"))
            {
                <span class="yes">@postDetails.Availability</span>
             }
             else
             {
                 <span class="no">@postDetails.Availability</span>
             }
             </span>
        <br/>
        <span><label style="font-weight:bold;">Donateur :</label> @postDetails.DonatingSubscriberLogin </span>
        <br/>
                @{
                    if (@postDetails.ReceivingSubscriberLogin != null )
                    {
                      <span><label style="font-weight:bold;">Bénéficiaire :</label> @postDetails.ReceivingSubscriberLogin </span> 
                      <br>
                    }
                }
        <span><label style="font-weight:bold;">Id Annonce :</label> @postDetails.Id </span>
        <br/>
        <span><label style="font-weight:bold;">Description :</label> @postDetails.Description </span>
        <br/>
        @{
                    if (@postDetails.IdStorage != 0)
                    {
                        <span><label style="font-weight:bold;">Emplacement :</label> @postDetails.IdStorage </span>
                        <br/>
                    }
                    else
                    {
                        <span style="font-weight:bold;">Remise en main propre</span>
                        <br/>
                    }
                }
        <span><label style="font-weight:bold;">Ville :</label> @postDetails.CityName </span>
         
        <div>
             <img src="~/images/upload/@postDetails.Picture" height="150"/>
            </div>            
            <br/>
            @{
                if (@postDetails.Availability == "En attente de validation")
                {
                    <a class="lien" asp-controller="DisplayAllPosts" asp-action="validate" asp-route-id="@postDetails.Id">Accepter</a>
                    <a class="lien"  asp-controller="DisplayAllPosts" asp-action="refuse" asp-route-id="@postDetails.Id">Refuser</a>
                } 
                else if (@postDetails.Availability == "Disponible")
                {
                        <a class="lien" asp-controller="DisplayAllPosts" asp-action="delete" asp-route-id="@postDetails.Id">Annuler le don</a>
                }
                else if (@postDetails.Availability == "En attente de dépot")
                {
                        <a class="lien" asp-controller="DisplayAllPosts" asp-action="delete" asp-route-id="@postDetails.Id">Annuler le don</a>   
                }
                else if (@postDetails.Availability == "Terminé")
                {
                    if (!@postDetails.IsRated)
                        {
                         <a class="lien" asp-controller="Rating" asp-action="IndexDonator" asp-route-id="@postDetails.Id">Noter la transaction</a>      
                        }
                }
                
                
            }
            <div class="formblockelement">
                <img src="~/Image/Strawberry.png" alt="strawberry" style="max-width:30px; max-height:30px;"/>
                <img src="~/Image/Strawberry.png" alt="strawberry" style="max-width:30px; max-height:30px;"/>
                <img src="~/Image/Strawberry.png" alt="strawberry" style="max-width:30px; max-height:30px;"/>
            </div>
            <br/>
    </div>
    }
    </div>
</section>

WebApp/Views/DisplayAllPosts/IndexReceiver.cshtml
@using Fr.EQL.AI110.DLD_GD.Entities
@using WebApp.Models

@model PostSearchViewModel

<h1>Mes réservations</h1>
<form method="post">
  <label class="white-font">Adhérent : </label>
        <select asp-for="IdDonatingSubscriber">
            <option value = "0"> Tous </option>
            @foreach (Subscriber subscriber in Model.Subscribers)
            {
                <option value="@subscriber.Id">@subscriber.Login</option>
            }
        </select>
        <input class="cute-button" type="submit" value="Filtrer"/>
</form>

<section>
    <div class="block">
    @foreach (PostDetails postDetails in Model.Posts)
    {
    <div class="block-elements">
        <div class="formblockelement">
                <img src="~/Image/Strawberry.png" alt="strawberry" style="max-width:30px; max-height:30px;"/>
            </div>
        <p class="post-title"> 
             <a asp-controller="DisplayAllPosts" asp-action="displaypost" asp-route-id="@postDetails.Id">@postDetails.Title</a>
            </p>
        <span><label style="font-weight:bold;">Date de publication :</label> @postDetails.PostDate.ToString("dd/MM/yyyy") </span> 
        <br/>
        <span><label style="font-weight:bold;">Disponibilité :</label>
            @if (@postDetails.Availability.Equals("Disponible"))
            {
                <span class="yes">@postDetails.Availability</span>
             }
             else
             {
                 <span class="no">@postDetails.Availability</span>
             }
             </span>
        <br/>
        <span><label style="font-weight:bold;">Bénéficiaire :</label> @postDetails.ReceivingSubscriberLogin </span>
        <br/>
         <span><label style="font-weight:bold;">Donateur :</label> @postDetails.DonatingSubscriberLogin </span>
        <br>
        <span><label style="font-weight:bold;">Id Annonce :</label> @postDetails.Id </span>
        <br/>
        <span><label style="font-weight:bold;">Description :</label> @postDetails.Description </span>
        <br/>
                @{
                    if (@postDetails.IdStorage != 0)
                    {
                        <span><label style="font-weight:bold;">Emplacement :</label> @postDetails.IdStorage </span>
                        <br/>
                    }
                    else
                    {
                        <span style="font-weight:bold;">Remise en main propre</span>
                        <br/>
                    }
                }
        
        <span><label style="font-weight:bold;">Ville :</label> @postDetails.CityName </span>
         
        <div>
             <img src="~/images/upload/@postDetails.Picture" height="150"/>
            </div>            
            <br/>
            @{
                if (@postDetails.Availability == "En attente de validation")
                {
                    <span>En attente de validation</span>
                }
                else if (@postDetails.Availability == "Disponible")
                {
                    <span>Votre réservation n'a pas été accepté</span><br />
                    <a class="lien" asp-controller="DisplayAllPosts" asp-action="ok" asp-route-id="@postDetails.Id">Enlever de la liste</a>
                }
                else if (@postDetails.Availability == "En attente de dépot")
                {
                     <span>En attente de dépot</span>
                     <br />
                        <a class="lien" asp-controller="DisplayAllPosts" asp-action="cancel" asp-route-id="@postDetails.Id">Annuler la réservation</a>
                    }
                    else if (@postDetails.Availability == "En attente de collecte")
                    {
                        if (@postDetails.IdStorage != 0 )
                        {
                            <span>Veuillez chercher votre colis au point de dépôt</span>

                        } else
                        {
                           <a class="lien" asp-controller="DisplayAllPosts" asp-action="confirmedcollection" asp-route-id="@postDetails.Id">Valider la collecte</a> 
                        }
                        
                }
                else if (@postDetails.Availability == "Terminé")
                { 
                        if (!@postDetails.IsRated)
                        {
                            <a class="lien" asp-controller="Rating" asp-action="Indexreceiver" asp-route-id="@postDetails.Id">Noter la transaction</a>  
                        }
                      
                }
                
                
            }
            <div class="formblockelement">
                <img src="~/Image/Strawberry.png" alt="strawberry" style="max-width:30px; max-height:30px;"/>
                <img src="~/Image/Strawberry.png" alt="strawberry" style="max-width:30px; max-height:30px;"/>
                <img src="~/Image/Strawberry.png" alt="strawberry" style="max-width:30px; max-height:30px;"/>
            </div>
            <br/>
    </div>
    }
    </div>
</section>