WebApp/Controllers/PostController.cs
using Fr.EQL.AI110.DLD_GD.Business;
using Fr.EQL.AI110.DLD_GD.Entities;
using WebApp.Models;
using Microsoft.AspNetCore.Mvc;


namespace Fr.EQL.AI110.DLD_GD.WebApp.Controllers
{
    public class PostController : Controller
    {
        public const int DEFAULT_DISTANCE = 50;
        public const int DEFAULT_CITY = 1;

        [HttpGet]
        public IActionResult Index()
        {
            PostSearchViewModel model = new PostSearchViewModel();

            PostBusiness postBU = new PostBusiness();
            model.Posts = postBU.GetPosts();

            CityBusiness cityBU = new CityBusiness();
            model.Cities = cityBU.GetCities();

            SubscriberBusiness subscriberBU = new SubscriberBusiness();
            model.Subscribers = subscriberBU.GetSubscribers();

            CategoryBusiness categoryBU = new CategoryBusiness();
            model.Categories = categoryBU.GetCategories();

            ProductLineBusiness productLineBU = new ProductLineBusiness();

            foreach (PostDetails post in model.Posts)
            {
                post.CityName = cityBU.GetCityById(post.IdCityOfDeposit).CityName;
                post.CityZipCode = cityBU.GetCityById(post.IdCityOfDeposit).ZipCode;
                if (subscriberBU.GetSubscriberById(post.IdDonatingSubscriber) != null)
                {
                    post.DonatingSubscriberLogin = subscriberBU.GetSubscriberById(post.IdDonatingSubscriber).Login;
                }
                post.ProductLineDetails = productLineBU.GetProductLineDetails(post.Id);
            }

            model.Posts = postBU.OrderByPostDate(model.Posts, model.DateOrder);

            return View(model);
        }


        [HttpPost]
        public IActionResult Index(PostSearchViewModel model)
        {
            PostBusiness postBU = new PostBusiness();
            int idSearchedCity = DEFAULT_CITY;

            if (model.IdSearchedCity != 0)
            {
                idSearchedCity = model.IdSearchedCity;
            }
            else
            {
                model.Distance = DEFAULT_DISTANCE;
            }
            
            CityBusiness cityBU = new CityBusiness();
            model.Cities = cityBU.GetCities();

            SubscriberBusiness subscriberBU = new SubscriberBusiness();
            model.Subscribers = subscriberBU.GetSubscribers();

            CategoryBusiness categoryBU = new CategoryBusiness();
            model.Categories = categoryBU.GetCategories();

            model.Posts = postBU.SearchPosts(model.Title, idSearchedCity, model.Distance, model.IdDonatingSubscriber, model.DateOrder, model.IdSearchedCategory);

            return View(model);
        }

        [HttpGet]
        [Route("Post/MyPosts/{userId}")]
        public IActionResult MyPosts(int userId)
        {
            PostSearchViewModel model = new PostSearchViewModel();

            PostBusiness postBU = new PostBusiness();

            model.Posts = postBU.GetPostsByIdSubscriber(userId);

            CityBusiness cityBU = new CityBusiness();
            model.Cities = cityBU.GetCities();

            SubscriberBusiness subscriberBU = new SubscriberBusiness();
            foreach (PostDetails post in model.Posts)
            {
                post.CityName = cityBU.GetCityById(post.IdCityOfDeposit).CityName;
                post.DonatingSubscriberLogin = subscriberBU.GetSubscriberById(post.IdDonatingSubscriber).Login;
            }

            return View(model);
        }

        public IActionResult DisplayPost(int id)
        {
            PostViewModel model = new PostViewModel();

            SubscriberBusiness subscriberBU = new SubscriberBusiness();
            model.Subscribers = subscriberBU.GetSubscribers();

            PostBusiness postBu = new PostBusiness();
            model.Post = postBu.GetPostById(id);

            ProductLineBusiness productLineBu = new ProductLineBusiness();
            model.ProductLine = productLineBu.GetProductLine(id);

            UnitBusiness unitBu = new UnitBusiness();
            model.Unit = unitBu.GetUnit(model.ProductLine.IdUnit);

            if (model.Post.IdStorage != 0)
            {
            StorageBusiness storageBusiness = new StorageBusiness();
            model.Storage = storageBusiness.GetStorage(model.Post.IdStorage);

            PickupPointBusiness pickupPointBusiness = new PickupPointBusiness();
            model.PickupPoint = pickupPointBusiness.GetPickupPoint(model.Storage.IdPickupPoint);
            }

            CityBusiness cityBusiness = new CityBusiness();
            model.City = cityBusiness.GetCityById(model.Post.IdCityOfDeposit);

            return View(model);
        }

        [HttpPost]
        public IActionResult BookPost(PostViewModel model)
        {

          PostBusiness postBusiness = new PostBusiness();
          Post post = postBusiness.GetPostById(model.Post.Id);
          post.IdReceivingSubscriber = model.Subscriber.Id;
          post.ReservationDate = DateTime.Now;
          postBusiness.Update(post);
          MailNotificationBusiness mailBU = new MailNotificationBusiness();

          SubscriberBusiness subBU = new SubscriberBusiness();
          Subscriber donator = subBU.GetSubscriberById(post.IdDonatingSubscriber);
          mailBU.NewReservationMail(donator);

          return View(model);
        }

       
    }
}

WebApp/Controllers/RatingController.cs
using Fr.EQL.AI110.DLD_GD.Business;
using Fr.EQL.AI110.DLD_GD.Entities;
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class RatingController : Controller
    {
        [HttpGet]
        public IActionResult IndexReceiver(int id)
        {
            RatingViewModel model = new RatingViewModel();
            model.IdPost = id;

            PostBusiness postBu = new PostBusiness();
            Post post = postBu.GetPostById(id);

            SubscriberBusiness subBu = new SubscriberBusiness();
            model.RatingSub = subBu.GetSubscriberById(post.IdReceivingSubscriber);
            model.RatedSub = subBu.GetSubscriberById(post.IdDonatingSubscriber);

            model.IsDonator = false;

            return View("Index",model);
        }
        [HttpPost]
        public IActionResult SaveRating(RatingViewModel model)
        {
            PostBusiness postBu = new PostBusiness();
            Post post = postBu.GetPostById(model.IdPost);

            SubscriberBusiness subBu = new SubscriberBusiness();
            RatingBusiness ratingBu = new RatingBusiness();
            model.Rating.IdPost = model.IdPost;

            if (model.IsDonator)
            {
                model.RatingSub = subBu.GetSubscriberById(post.IdDonatingSubscriber);
                model.RatedSub = subBu.GetSubscriberById(post.IdReceivingSubscriber);

                model.Rating.IdSubscriber = post.IdDonatingSubscriber;
                model.Rating.IdReceivingSub = post.IdReceivingSubscriber;
                
            }
            else
            {
                model.RatingSub = subBu.GetSubscriberById(post.IdReceivingSubscriber);
                model.RatedSub = subBu.GetSubscriberById(post.IdDonatingSubscriber);

                model.Rating.IdSubscriber = post.IdReceivingSubscriber;
                model.Rating.IdReceivingSub = post.IdDonatingSubscriber;
            }

            ratingBu.Save(model.Rating);
            model.Message = "Votre note a bien été prise en compte";

            return View("Index",model);
        }

        public IActionResult IndexDonator(int id)
        {
            RatingViewModel model = new RatingViewModel();
            model.IdPost = id;

            PostBusiness postBu = new PostBusiness();
            Post post = postBu.GetPostById(id);

            SubscriberBusiness subBu = new SubscriberBusiness();
            model.RatingSub = subBu.GetSubscriberById(post.IdDonatingSubscriber); 
            model.RatedSub = subBu.GetSubscriberById(post.IdReceivingSubscriber);

            RatingBusiness ratBu = new RatingBusiness();
            model.Rating = ratBu.GetRatingByIdPost(model.RatingSub.Id, model.IdPost);

            model.IsDonator = true;

            return View("Index", model);
        }

        public IActionResult Display()
        {
            RatingViewModel model = new RatingViewModel();

            SubscriberBusiness subBu = new SubscriberBusiness();
            model.Subscribers = subBu.GetSubscribers();

            RatingBusiness ratBu = new RatingBusiness();
            model.Ratings = ratBu.GetRatings(0);

            return View(model);
        }
        [HttpPost]
        public IActionResult Display(RatingViewModel model)
        {
            SubscriberBusiness subBu = new SubscriberBusiness();
            model.Subscribers = subBu.GetSubscribers();

            RatingBusiness ratBu = new RatingBusiness();
            model.Ratings = ratBu.GetRatings(model.RatedSub.Id);

            return View(model);
        }

    }
}

WebApp/Controllers/TokenController.cs
using Fr.EQL.AI110.DLD_GD.Business;
using Fr.EQL.AI110.DLD_GD.Entities;
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class TokenController : Controller
    {
        public IActionResult Index()
        {
            TokenViewModel model = new TokenViewModel();

            SubscriberBusiness subBu = new SubscriberBusiness();
            model.Subscribers = subBu.GetSubscribers();

            return View(model);
        }

        [HttpPost]
        public IActionResult Index(TokenViewModel model)
        {

            SubscriberBusiness subBu = new SubscriberBusiness();
            model.Subscribers = subBu.GetSubscribers();

            PostBusiness postBu = new PostBusiness();
            model.Donation = postBu.GetPastDonations(model.Subscriber.Id).Count;
            model.Received = postBu.GetPastReservations(model.Subscriber.Id).Count;

            PurchaseTokenBusiness purchaseBu = new PurchaseTokenBusiness();
            model.Amount = purchaseBu.GetAmountsOfIdSub(model.Subscriber.Id) + model.Donation/2 - model.Received;



            return View(model);
        }
        [HttpPost]
        public IActionResult BuyToken(TokenViewModel model)
        {
            SubscriberBusiness subBu = new SubscriberBusiness();
            model.Subscriber = subBu.GetSubscriberById(model.Subscriber.Id);

            PurchaseTokenBusiness purchaseBu = new PurchaseTokenBusiness();
            model.Amount = purchaseBu.GetAmountsOfIdSub(model.Subscriber.Id);

            TokenBundleBusiness bundleBu = new TokenBundleBusiness();
            model.Bundles = bundleBu.GetTokenBundles();

            return View(model);
            
        }
        public IActionResult Calculate(TokenViewModel model)
        {
            SubscriberBusiness subBu = new SubscriberBusiness();
            model.Subscriber = subBu.GetSubscriberById(model.Subscriber.Id);

            PurchaseTokenBusiness purchaseBu = new PurchaseTokenBusiness();
            model.Amount = purchaseBu.GetAmountsOfIdSub(model.Subscriber.Id);

            TokenBundleBusiness bundleBu = new TokenBundleBusiness();
            if (Request.Form["token"] != "")
            {
                int bundle = int.Parse(Request.Form["token"]);
                float price = bundleBu.GetTokenBundle(bundle).BundlePrice;
                model.Calculate = price * model.PurchaseLine.Quantity;
            }

            model.Bundles = bundleBu.GetTokenBundles();

            return View("BuyToken",model);
        }
        public IActionResult Purchase(TokenViewModel model)
        {
            SubscriberBusiness subBu = new SubscriberBusiness();
            //model.Subscribers = subBu.GetSubscribers();
            model.Subscriber = subBu.GetSubscriberById(model.Subscriber.Id);

            TokenBundleBusiness tokenBu = new TokenBundleBusiness();
            model.Bundles = tokenBu.GetTokenBundles();
            int bundle = int.Parse(Request.Form["token"]);

            PurchaseTokenBusiness tokenPurchaseBu = new PurchaseTokenBusiness();
            TokenPurchase token = new TokenPurchase();
            token.IdSubscriber = model.Subscriber.Id;
            if(model.PurchaseLine.Quantity == 0)
            {
                model.PurchaseLine.Quantity = 1;
            }
            token.TokensNumber = tokenBu.GetTokenBundle(bundle).BundleAmount*model.PurchaseLine.Quantity;
            token.PurchaseAmount = tokenBu.GetTokenBundle(bundle).BundlePrice*model.PurchaseLine.Quantity;
            tokenPurchaseBu.SaveToken(token);

            PurchaseLineBusiness lineBu = new PurchaseLineBusiness();
            PurchaseLine line = new PurchaseLine();
            line.IdTokenPurchase = token.Id;
            line.IdTokenBundle = bundle;
            line.Quantity = model.PurchaseLine.Quantity;
            lineBu.SavePurchaseLine(line);

            model.Message = "Votre achat de crédit a bien été pris en compte";

            return View("BuyToken",model);
        }
    }
}

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>
    <link runat="server" rel="icon" href="~/favicon.ico" type="image/ico"/>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DLD</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Dashboard">Tableau de Bord</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Publication" asp-action="AIndex">Publier une annonce</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Post" asp-action="Index">Rechercher une annonce</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DisplayAllPosts" asp-action="Index">Voir mes dons</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DisplayAllPosts" asp-action="Indexreceiver">Voir mes réservations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Token" asp-action="Index">Cagnotte</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PickupPoint" asp-action="Index">Points de Dépôts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Rating" asp-action="Display">Voir mes notations</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer >

    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>